# -*- coding: utf-8 -*-
"""4_OBJ_SIM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu8PZS6B8mrLc-qyXQWorCGSPlyyBWjC
"""

# Dynamic Obstacle-Adaptive Robot Navigation Simulation (curvilinear/randomized obstacles)
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML
import random
import math

random.seed(42)
np.random.seed(42)

# ------------------------------------------------------------
# 1. ENVIRONMENT
# ------------------------------------------------------------
class DynamicEnv:
    def __init__(self, size=10, dt=1.0):
        self.size = size
        self.dt = dt
        self.goal = (size - 1, size - 1)
        self.robot = (0, 0)

        # Obstacles: [x, y, speed, heading (rad), angular_noise_scale, speed_noise_scale]
        # Choose different centers / radii implicitly by initial pos/speed/heading
        self.obstacles = [
            [4.0, 4.0, 0.7, math.radians(20), 0.2, 0.05],
            [7.0, 2.0, 1.0, math.radians(-120), 0.25, 0.06],
            [2.0, 6.0, 0.8, math.radians(90), 0.18, 0.04],
        ]

    def reset(self):
        self.robot = (0, 0)
        return self.robot

    def move_obstacles(self):
        """Move obstacles with curvilinear (steering) motion and light randomness."""
        for obs in self.obstacles:
            x, y, speed, heading, ang_noise, spd_noise = obs

            # random smooth steering: small gaussian change to heading
            d_heading = np.random.normal(scale=ang_noise) * 0.1
            heading += d_heading

            # small speed variation so motion isn't strictly periodic
            speed += np.random.normal(scale=spd_noise) * 0.02
            # clamp speed to a reasonable band
            speed = float(np.clip(speed, 0.2, 1.5))

            # update position (continuous)
            dx = speed * math.cos(heading) * self.dt
            dy = speed * math.sin(heading) * self.dt
            x += dx
            y += dy

            # Bounce off borders but preserve smoothness: reflect heading when hitting wall
            bounced = False
            if x <= 0:
                x = 0
                heading = math.pi - heading
                bounced = True
            if x >= self.size - 1:
                x = self.size - 1
                heading = math.pi - heading
                bounced = True
            if y <= 0:
                y = 0
                heading = -heading
                bounced = True
            if y >= self.size - 1:
                y = self.size - 1
                heading = -heading
                bounced = True

            # If bounced, add a bit of randomness to avoid repeating exact path
            if bounced:
                heading += np.random.normal(scale=0.2)

            # Store back
            obs[0] = x
            obs[1] = y
            obs[2] = speed
            obs[3] = heading

    def predict_obstacles(self, steps=1):
        """Predict positions after `steps` steps, using current speed & heading.
           Returns a list of (px, py) floats for next step (or multiple-step prediction if wanted)."""
        preds = []
        for obs in self.obstacles:
            x, y, speed, heading, _, _ = obs
            # Simulate forward 'steps' times using same heading and speed (simple short-term prediction)
            px = x + speed * math.cos(heading) * self.dt * steps
            py = y + speed * math.sin(heading) * self.dt * steps
            preds.append((px, py))
        return preds

    def inside_bounds(self, x):
        return 0 <= x < self.size

    def step(self, action):
        x, y = self.robot

        # Robot actions (grid moves)
        # 0: down (+x), 1: up (-x), 2: right (+y), 3: left (-y)
        if action == 0:
            x += 1
        elif action == 1:
            x -= 1
        elif action == 2:
            y += 1
        elif action == 3:
            y -= 1
        else:
            # no-op or invalid action
            pass

        # Keep robot in bounds (grid)
        x = int(np.clip(x, 0, self.size - 1))
        y = int(np.clip(y, 0, self.size - 1))
        self.robot = (x, y)

        # Move obstacles (continuous)
        self.move_obstacles()
        predicted = self.predict_obstacles(steps=1)

        # Collision checks: if robot exactly at an obstacle continuous position rounded to int
        for ox, oy, *_ in self.obstacles:
            # round obstacle continuous pos to nearest integer grid cell to check collision
            if (x, y) == (int(round(ox)), int(round(oy))):
                return self.robot, -100, True

        # Avoid predicted collisions: if any predicted rounded position equals robot's intended grid cell
        for px, py in predicted:
            if (x, y) == (int(round(px)), int(round(py))):
                return self.robot, -10, False

        # Goal
        if self.robot == self.goal:
            return self.robot, 100, True

        return self.robot, -1, False


# ------------------------------------------------------------
# 2. ADAPTIVE POLICY (Greedy + Prediction Avoidance)
# ------------------------------------------------------------
def choose_action(env):
    rx, ry = env.robot
    gx, gy = env.goal

    # Greedy toward goal in Manhattan sense, prefer x-movement if equal
    dx = gx - rx
    dy = gy - ry
    if abs(dx) >= abs(dy):
        action = 0 if dx > 0 else 1 if dx < 0 else (2 if dy > 0 else 3)
    else:
        action = 2 if dy > 0 else 3 if dy < 0 else (0 if dx > 0 else 1)

    # Check predicted obstacle positions (rounded to grid) + a small neighborhood (safety margin)
    preds = env.predict_obstacles(steps=1)
    # build set of unsafe grid cells (predicted + neighbors)
    unsafe = set()
    for px, py in preds:
        gxcell = int(round(px))
        gycell = int(round(py))
        for nx in (gxcell - 1, gxcell, gxcell + 1):
            for ny in (gycell - 1, gycell, gycell + 1):
                if 0 <= nx < env.size and 0 <= ny < env.size:
                    unsafe.add((nx, ny))

    # If planned action moves into an unsafe cell, try alternatives (prefer moves that still go to goal)
    def resulting_cell(a):
        x, y = rx, ry
        if a == 0: x += 1
        if a == 1: x -= 1
        if a == 2: y += 1
        if a == 3: y -= 1


        x = int(np.clip(x, 0, env.size - 1))
        y = int(np.clip(y, 0, env.size - 1))
        return (x, y)

    intended = resulting_cell(action)
    if intended in unsafe:
        # try other actions, sorted by closeness to goal after move
        alternatives = [0, 1, 2, 3]
        alternatives.remove(action)
        scored = []
        for a in alternatives:
            cell = resulting_cell(a)
            if cell in unsafe:
                score = float('inf')  # bad
            else:
                # prefer actions that reduce Manhattan distance to goal
                score = abs(env.goal[0] - cell[0]) + abs(env.goal[1] - cell[1])
            scored.append((score, a, cell))
        scored.sort()
        # pick best safe alternative (if all are unsafe we'll still pick the best one)
        best_score, best_action, best_cell = scored[0]
        action = best_action

    return action


# ------------------------------------------------------------
# 3. ANIMATION SETUP
# ------------------------------------------------------------
env = DynamicEnv(size=10)

fig, ax = plt.subplots(figsize=(6, 6))
ax.set_xlim(-1, env.size)
ax.set_ylim(-1, env.size)
ax.set_xticks(np.arange(env.size))
ax.set_yticks(np.arange(env.size))
ax.grid(True)

robot_plot, = ax.plot([], [], 'bo', markersize=10, label="Robot")
goal_plot, = ax.plot(env.goal[0], env.goal[1], 'go', markersize=12, label="Goal")
# obstacle main markers (continuous, red squares)
obs_plots = [ax.plot([], [], marker='s', linestyle='None', markersize=10)[0] for _ in env.obstacles]
# predicted next positions (smaller yellow markers)
pred_plots = [ax.plot([], [], marker='s', linestyle='None', markersize=6)[0] for _ in env.obstacles]

plt.legend(loc="upper left")

def init():
    robot_plot.set_data([], [])
    for op in obs_plots:
        op.set_data([], [])
    for pp in pred_plots:
        pp.set_data([], [])
    return [robot_plot] + obs_plots + pred_plots

def update(frame):
    action = choose_action(env)
    next_state, reward, done = env.step(action)

    # Plot robot (grid position)
    robot_plot.set_data([next_state[0]], [next_state[1]])

    # Update obstacles (continuous positions)
    for i, obs in enumerate(env.obstacles):
        ox, oy, _, _, _, _ = obs
        obs_plots[i].set_data([ox], [oy])

    # Update predicted obstacle positions (one-step forecast)
    preds = env.predict_obstacles(steps=1)
    for i, p in enumerate(preds):
        pred_plots[i].set_data([p[0]], [p[1]])

    if done:
        ani.event_source.stop()

    return [robot_plot] + obs_plots + pred_plots

ani = animation.FuncAnimation(
    fig,
    update,
    init_func=init,
    frames=1000,
    interval=200,
    blit=True
)

# DISPLAY ANIMATION IN JUPYTER / COLAB
animation_html = ani.to_jshtml()
HTML(animation_html)